{{- if .Values.rest.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm.fullname" . }}-rest
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "helm.fullname" . }}-rest
    weight: 100
  port:
    targetPort: {{ .Values.rest.service.targetPort }}-tcp
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}