# Copyright 2022 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app.kubernetes.io/component: worker

rules: 
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - create
  - get
  - patch
  - delete
  - list

- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - patch
  - delete
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  - pods
  verbs:
  - create
  - patch
  - list
  - get
  - delete

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch

- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - patch
  - delete
  - list

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rest.worker.serviceAccount.name }}
    namespace: {{ .Values.rest.namespace }}
roleRef:
  kind: Role
  name: {{ include "helm.fullname" . }}
  apiGroup: rbac.authorization.k8s.io