kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app.kubernetes.io/component: worker

rules: 
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - create
  - get
  - patch
  - delete
  - list

- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - patch
  - delete
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  - pods
  verbs:
  - create
  - patch
  - list
  - get
  - delete

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch

- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - patch
  - delete
  - list

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rest.worker.serviceAccount.name }}
    namespace: {{ .Values.rest.namespace }}
roleRef:
  kind: Role
  name: {{ include "helm.fullname" . }}
  apiGroup: rbac.authorization.k8s.io