CREATE TABLE LOGS
(
    id INT auto_increment PRIMARY KEY,
    LOG_DATE   DATETIME NOT NULL,
    LOGGER  VARCHAR2(250)    NOT NULL,
    LOG_LEVEL   VARCHAR2(10)    NOT NULL,
    MESSAGE VARCHAR2(1000)  NOT NULL
);