window.REACT_APP_API_PLATFORM="test"
window.REACT_APP_KAI_REST_API_HOST="http://gaas-rest-kai-helm-3.apps.ocp1.purplesky-harmony.co.uk"
window.REACT_APP_COGNITO_USERPOOLID="us-east-1_ABC1def2g"
window.REACT_APP_COGNITO_CLIENTID="42ov9u4hs69oji3y357aq26era"
window.SKIP_PREFLIGHT_CHECK="true"