window.REACT_APP_API_PLATFORM = 'OPENSHIFT';
window.REACT_APP_KAI_REST_API_HOST = 'http://localhost:4000';
window.REACT_APP_COGNITO_USERPOOLID = '';
window.REACT_APP_COGNITO_CLIENTID = '';
window.SKIP_PREFLIGHT_CHECK = 'true';
