window.REACT_APP_API_PLATFORM="AWS"
window.REACT_APP_KAI_REST_API_HOST="https://MY_API_LOCATION.execute-api.us-east-1.amazonaws.com/prod"
window.REACT_APP_COGNITO_USERPOOLID="us-east-1_ABC1def2g"
window.REACT_APP_COGNITO_CLIENTID="42ov9u4hs69oji3y357aq26era"
window.SKIP_PREFLIGHT_CHECK="true"