{{- if .Values.rest.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-rest
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helm.fullname" . }}-rest-service-account
      containers:
          - image: "{{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag | default .Chart.AppVersion }}"
            name: gaas-rest
            envFrom:
              - configMapRef:
                  name: {{ include "helm.fullname" . }}-rest
            resources:
              requests:
                memory: "1Gi"

          - image: DOCKER_USERNAME/GAAS-SIDECAR-IMAGE_NAME
            imagePullPolicy: Always
            name: jwt-sidecar-app
            ports:
               - containerPort: 8081
                 protocol: TCP
          - image: DOCKER_USERNAME/GAAS-EUREKA-IMAGE_NAME
            imagePullPolicy: Always
            name: eureka-app
            ports:
               - containerPort: 8761
                 protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 8081
              initialDelaySeconds: 120
              timeoutSeconds: 3
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 5
            livenessProbe:
              tcpSocket:
                port: 8081
              initialDelaySeconds: 120
              timeoutSeconds: 3
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 5
  {{- end }}
