name: Code Analysis and Clean
on: [push, pull_request]

jobs:
  run-maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run build
        run: mvn clean install
  run-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gaas-ui/

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install dependencies
        run:
          npm install

      - name: Run tests
        run:
          npm run test
      - name: Lint code
        run:
          npm run lint-errors
  run-semgrep:
    name: Scan
    needs: [run-maven-build, run-ui-tests]
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config:
            p/r2c
            p/owasp-top-ten
            p/r2c-ci
            p/xss
            p/ci
            p/jwt
            p/nodejs
            p/nodejsscan
          auditOn: push
          generateSarif: "1"
      - name: Github Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
