name: Code Analysis
on: [ push, pull_request ]

jobs:
  run-maven-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gaffer-as-a-service
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run build
        run: mvn clean install
      - name: Build with Maven
        run: mvn -B verify -P coverage
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.1.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            gaffer-as-a-service/gaas-rest/target/site/jacoco/jacoco.csv
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: jacoco-report-uploader # optional
          fail_ci_if_error: true # optional (default = false)
      - name: Upload Dependancy Check Results
        uses: actions/upload-artifact@master
        with:
          name: GAAS-Dependancy-Report
          path: ${{github.workspace}}/gaffer-as-a-service/gaas-rest/target/dependency-check-report.html
  run-ui-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gaas-ui/

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install dependencies
        run:
          npm install
      - name: Lint code
        run:
          npm run lint-errors
      - name: Dependancy Check
        run: npm run owasp
      - name: Upload Dependancy Check Results
        uses: actions/upload-artifact@master
        with:
          name: UI-Dependancy-Report
          path: ${{github.workspace}}/gaas-ui/dependency-check-reports
  run-semgrep:
    name: Semgrep Scan
    needs: [ run-maven-build, run-ui-code-analysis ]
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config:
            p/r2c
            p/owasp-top-ten
            p/r2c-ci
            p/xss
            p/ci
            p/jwt
            p/nodejs
            p/nodejsscan
          auditOn: push
          generateSarif: "1"
      - name: Github Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
